# Generated by Django 4.2.7 on 2026-07-13 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employes', '0006_remove_employe_poste_employe_fonction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objectifs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_evaluation', models.DateField(auto_now_add=True)),
                ('ponctualite', models.IntegerField(default=0)),
                ('discipline', models.IntegerField(default=0)),
                ('performance', models.IntegerField(default=0)),
                ('commentaire', models.TextField(blank=True)),
                ('score_total', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_objectifs', to='employes.employe')),
                ('evaluateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('objectif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='objectifs.objectif')),
            ],
        ),
    ]
