# Generated by Django 5.2.8 on 2026-05-11 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0002_remove_employe_user_employe_quartier'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='user',
            name='commercial',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='user',
            name='technicien',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telephone',
        ),
        migrations.AddField(
            model_name='user',
            name='employe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='employes.employe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('superviseur', 'Superviseur'), ('commercial', 'Commercial'), ('technicien', 'Technicien'), ('comptable', 'Comptable'), ('rh', 'Ressources Humaines')], max_length=20),
        ),
    ]
