# Generated by Django 4.2.7 on 2026-04-09 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('type_contrats', '0001_initial'),
        ('base_stations', '__first__'),
        ('commercials', '0004_alter_commercial_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=255)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('quartier', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vlan', models.CharField(blank=True, max_length=10, null=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('statut', models.CharField(default='non_actif', max_length=20)),
                ('capacite', models.CharField(blank=True, max_length=5, null=True)),
                ('download', models.CharField(blank=True, max_length=5, null=True)),
                ('upload', models.CharField(blank=True, max_length=5, null=True)),
                ('contrat_pdf', models.FileField(blank=True, null=True, upload_to='contrats/')),
                ('username_pppoe', models.CharField(blank=True, max_length=100, null=True)),
                ('statut_paiement', models.CharField(default='impaye', max_length=20)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('base_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_stations.basestation')),
                ('commercial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercials.commercial')),
                ('type_contrat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='type_contrats.typecontrat')),
            ],
        ),
    ]
