# Generated by Django 4.2.7 on 2026-04-17 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('commercials', '0001_initial'),
        ('type_contrats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='commercial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercials.commercial'),
        ),
        migrations.AddField(
            model_name='client',
            name='type_contrat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='type_contrats.typecontrat'),
        ),
    ]
