# Generated by Django 4.2.7 on 2026-04-20 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date_conversion',
        ),
        migrations.RemoveField(
            model_name='client',
            name='type_client',
        ),
    ]
