# Generated by Django 4.2.7 on 2026-04-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_date_conversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='forfait',
            field=models.CharField(blank=True, choices=[('didié', 'Didié'), ('partagé', 'Partagé')], max_length=50, null=True),
        ),
    ]
