# Generated by Django 4.2.7 on 2026-04-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_forfait'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_suppression',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='est_supprime',
            field=models.BooleanField(default=False),
        ),
    ]
