# Generated by Django 5.2.8 on 2026-05-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='user',
        ),
        migrations.AddField(
            model_name='employe',
            name='quartier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
