# Generated by Django 5.2.8 on 2026-05-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0002_remove_employe_user_employe_quartier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
