# Generated by Django 5.2.8 on 2026-05-12 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0004_alter_employe_date_embauche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='departement',
        ),
        migrations.AlterField(
            model_name='employe',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employes.poste'),
        ),
        migrations.DeleteModel(
            name='Departement',
        ),
    ]
