# Generated by Django 4.2.7 on 2026-05-13 09:59

from django.db import migrations, models


def migrate_poste_to_fonction(apps, schema_editor):
    Employe = apps.get_model('employes', 'Employe')
    Poste = apps.get_model('employes', 'Poste')
    mapping = {
        'commercial': 'commercial',
        'technicien': 'technicien',
    }

    for employe in Employe.objects.all():
        if employe.poste_id:
            try:
                poste = Poste.objects.get(pk=employe.poste_id)
            except Poste.DoesNotExist:
                continue

            poste_name = poste.nom.strip().lower()
            if 'commercial' in poste_name:
                employe.fonction = mapping['commercial']
            elif 'technicien' in poste_name:
                employe.fonction = mapping['technicien']
            else:
                employe.fonction = None
            employe.save(update_fields=['fonction'])


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0005_remove_employe_departement_alter_employe_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='fonction',
            field=models.CharField(blank=True, choices=[('commercial', 'Commercial'), ('technicien', 'Technicien')], max_length=20, null=True),
        ),
        migrations.RunPython(migrate_poste_to_fonction, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='employe',
            name='poste',
        ),
    ]
