# Generated by Django 4.2.7 on 2026-04-09 15:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('techniciens', '0005_alter_technicien_id'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champrapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomChamp', models.CharField(max_length=100)),
                ('typeActivites', models.CharField(max_length=100)),
                ('typeChamp', models.CharField(choices=[('texte', 'Texte'), ('nombre', 'Nombre'), ('date', 'Date'), ('image', 'Image')], default='texte', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activite', models.CharField(choices=[('dementelement', 'Démantèlement'), ('survey', 'Survey'), ('installation', 'Installation'), ('investigation', 'Investigation'), ('maintenance', 'Maintenance'), ('tirage_FO', 'Tirage_FO'), ('raccordement', 'Raccordement'), ('remplacement', 'Remplacement'), ('noc support', 'Noc Support'), ('autre', 'Autre')], max_length=50, verbose_name="Type d'activité")),
                ('date_activite', models.DateField(default=datetime.date.today, verbose_name="Date de l'activité")),
                ('heure_debut', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description détaillée')),
                ('lieu', models.CharField(blank=True, max_length=20, null=True, verbose_name='Lieu')),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé'), ('reporte', 'Reporté')], default='planifie', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Client')),
                ('techniciens', models.ManyToManyField(blank=True, related_name='activites', to='techniciens.technicien')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'db_table': 'activites_activite',
                'ordering': ['-date_activite', 'heure_debut'],
            },
        ),
    ]
