# Generated by Django 4.2.7 on 2026-04-17 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercials', '0001_initial'),
        ('activites', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to='commercials.commercial'),
        ),
    ]
