# Generated by Django 4.2.7 on 2026-04-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('techniciens', '0001_initial'),
        ('activites', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='techniciens',
            field=models.ManyToManyField(blank=True, related_name='activites', to='techniciens.technicien'),
        ),
    ]
