# Generated by Django 4.2.7 on 2026-04-20 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_forfait'),
        ('activites', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='client',
            field=models.ForeignKey(blank=True, db_column='client_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='Client'),
        ),
    ]
