# Generated by Django 4.2.7 on 2026-03-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0004_alter_activite_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champrapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomChamp', models.CharField(max_length=100)),
                ('typeActivites', models.CharField(max_length=100)),
                ('typeChamp', models.CharField(choices=[('texte', 'Texte'), ('nombre', 'Nombre'), ('date', 'Date'), ('image', 'Image')], default='texte', max_length=20)),
            ],
        ),
    ]
