# Generated by Django 4.2.7 on 2026-04-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0005_alter_activite_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='statut',
            field=models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('en_attente', 'En attente')], default='planifie', max_length=20, verbose_name='Statut'),
        ),
    ]
