# Generated by Django 4.2.7 on 2026-03-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0005_champrapport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='type_activite',
            field=models.CharField(choices=[('dementelement', 'Démantèlement'), ('survey', 'Survey'), ('installation', 'Installation'), ('investigation', 'Investigation'), ('maintenance', 'Maintenance'), ('tirage_FO', 'Tirage_FO'), ('raccordement', 'Raccordement'), ('remplacement', 'Remplacement'), ('noc support', 'Noc Support'), ('autre', 'Autre')], max_length=50, verbose_name="Type d'activité"),
        ),
    ]
