# Generated by Django 4.2.7 on 2026-04-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('quartier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quartier')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse complète')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='techniciens/photos/', verbose_name='Photo')),
                ('specialite', models.CharField(blank=True, max_length=100, null=True, verbose_name='Spécialité')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('congé', 'En congé'), ('mission', 'En mission')], default='actif', max_length=20, verbose_name='Statut')),
                ('est_actif', models.BooleanField(default=True)),
                ('date_embauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Technicien',
                'verbose_name_plural': 'Techniciens',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
