# Generated by Django 5.2.8 on 2026-05-11 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0002_remove_employe_user_employe_quartier'),
        ('techniciens', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicien',
            options={'ordering': ['employe__nom', 'employe__prenom'], 'verbose_name': 'Technicien', 'verbose_name_plural': 'Techniciens'},
        ),
        migrations.RemoveField(
            model_name='technicien',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='technicien',
            name='date_embauche',
        ),
        migrations.RemoveField(
            model_name='technicien',
            name='email',
        ),
        migrations.RemoveField(
            model_name='technicien',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='technicien',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='technicien',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='technicien',
            name='quartier',
        ),
        migrations.RemoveField(
            model_name='technicien',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='technicien',
            name='user',
        ),
        migrations.AddField(
            model_name='technicien',
            name='employe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technicien_profile', to='employes.employe'),
        ),
    ]
