# Generated by Django 4.2.7 on 2026-05-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techniciens', '0003_alter_technicien_options_remove_technicien_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicien',
            name='specialite',
        ),
    ]
