# Generated by Django 4.2.7 on 2026-03-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techniciens', '0004_technicien_est_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicien',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
