# Generated by Django 4.2.7 on 2026-04-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techniciens', '0005_alter_technicien_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicien',
            name='adresse',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse complète'),
        ),
        migrations.AlterField(
            model_name='technicien',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='technicien',
            name='quartier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Quartier'),
        ),
        migrations.AlterField(
            model_name='technicien',
            name='specialite',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spécialité'),
        ),
        migrations.AlterField(
            model_name='technicien',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
    ]
