# Generated by Django 4.2.7 on 2026-04-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techniciens', '0006_alter_technicien_adresse_alter_technicien_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicien',
            name='date_embauche',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'embauche"),
        ),
    ]
