# Generated by Django 4.2.7 on 2026-04-17 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('techniciens', '0001_initial'),
        ('rapportActivites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportactivite',
            name='technicien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_activites', to='techniciens.technicien', verbose_name='Technicien'),
        ),
    ]
