# Generated by Django 4.2.7 on 2026-03-17 10:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0004_alter_activite_id'),
        ('rapportActivites', '0002_alter_rapportactivite_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_champ', models.CharField(choices=[('text', 'Texte'), ('number', 'Nombre'), ('textarea', 'Long texte'), ('select', 'Liste'), ('date', 'Date')], max_length=20)),
                ('obligatoire', models.BooleanField(default=False)),
                ('options', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='rapportactivite',
            options={},
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='client_present',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='commentaire_client',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='commentaire_validation',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='date_intervention_reelle',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='date_prochaine_intervention',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='date_rapport',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='date_validation',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='debit_constate',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='difficultes_rencontrees',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='document_joint',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='equipements_utilises',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='etat_apres',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='etat_avant',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='heure_debut_reelle',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='heure_fin_reelle',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='materiel_consomme',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='materiel_remplace',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='parametres_configures',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='photo_apres',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='photo_avant',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='prochaine_action',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='qualite_signal',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='recommandations',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='satisfaction_client',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='solutions_apportees',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='technicien',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='travaux_realises',
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='valide_par',
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rapportactivite',
            name='activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activites.activite'),
        ),
        migrations.AlterField(
            model_name='rapportactivite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='rapportactivite',
            table=None,
        ),
        migrations.CreateModel(
            name='ValeurChamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.TextField()),
                ('champ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapportActivites.champrapport')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapportActivites.rapportactivite')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rapports/photos/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rapportActivites.rapportactivite')),
            ],
        ),
        migrations.AddField(
            model_name='champrapport',
            name='type_activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapportActivites.typeactivite'),
        ),
    ]
