# Generated by Django 4.2.7 on 2026-04-17 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rapportActivites', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportactivite',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
    ]
