# Generated by Django 4.2.7 on 2026-03-17 12:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activites', '0005_champrapport'),
        ('techniciens', '0005_alter_technicien_id'),
        ('rapportActivites', '0003_champrapport_typeactivite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photorapport',
            name='rapport',
        ),
        migrations.RemoveField(
            model_name='valeurchamp',
            name='champ',
        ),
        migrations.RemoveField(
            model_name='valeurchamp',
            name='rapport',
        ),
        migrations.AlterModelOptions(
            name='rapportactivite',
            options={'ordering': ['-date_rapport'], 'verbose_name': "Rapport d'activité", 'verbose_name_plural': "Rapports d'activités"},
        ),
        migrations.RemoveField(
            model_name='rapportactivite',
            name='date_creation',
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='client_present',
            field=models.BooleanField(default=True, verbose_name='Client présent'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='commentaire_client',
            field=models.TextField(blank=True, verbose_name='Commentaire client'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='commentaire_validation',
            field=models.TextField(blank=True, verbose_name='Commentaire de validation'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='date_intervention_reelle',
            field=models.DateField(default=datetime.date.today, verbose_name="Date réelle d'intervention"),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='date_prochaine_intervention',
            field=models.DateField(blank=True, null=True, verbose_name='Date prochaine intervention'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='date_rapport',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création du rapport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='debit_constate',
            field=models.CharField(blank=True, max_length=50, verbose_name='Débit constaté'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='difficultes_rencontrees',
            field=models.TextField(blank=True, verbose_name='Difficultés rencontrées'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='document_joint',
            field=models.FileField(blank=True, null=True, upload_to='rapports/documents/', verbose_name='Document joint'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='equipements_utilises',
            field=models.TextField(blank=True, verbose_name='Équipements utilisés'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='etat_apres',
            field=models.TextField(default='', verbose_name='État après intervention'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='etat_avant',
            field=models.TextField(default='Initial', verbose_name='État avant intervention'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='heure_debut_reelle',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure début réelle'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='heure_fin_reelle',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure fin réelle'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='materiel_consomme',
            field=models.TextField(blank=True, verbose_name='Matériel consommé'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='materiel_remplace',
            field=models.TextField(blank=True, verbose_name='Matériel remplacé'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='parametres_configures',
            field=models.TextField(blank=True, verbose_name='Paramètres configurés'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='photo_apres',
            field=models.ImageField(blank=True, null=True, upload_to='rapports/photos/apres/', verbose_name='Photo après'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='photo_avant',
            field=models.ImageField(blank=True, null=True, upload_to='rapports/photos/avant/', verbose_name='Photo avant'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='prochaine_action',
            field=models.CharField(blank=True, max_length=200, verbose_name='Prochaine action'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='qualite_signal',
            field=models.CharField(blank=True, max_length=50, verbose_name='Qualité du signal'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='recommandations',
            field=models.TextField(blank=True, verbose_name='Recommandations'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='satisfaction_client',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Très insatisfait'), (2, '2 - Insatisfait'), (3, '3 - Moyen'), (4, '4 - Satisfait'), (5, '5 - Très satisfait')], null=True, verbose_name='Satisfaction client'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='solutions_apportees',
            field=models.TextField(blank=True, verbose_name='Solutions apportées'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='brouillon', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='technicien',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rapports_activites', to='techniciens.technicien', verbose_name='Technicien'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='travaux_realises',
            field=models.TextField(default='', verbose_name='Travaux réalisés'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AlterField(
            model_name='rapportactivite',
            name='activite',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='activites.activite', verbose_name='Activité concernée'),
        ),
        migrations.AlterModelTable(
            name='rapportactivite',
            table='activites_rapport',
        ),
        migrations.DeleteModel(
            name='ChampRapport',
        ),
        migrations.DeleteModel(
            name='PhotoRapport',
        ),
        migrations.DeleteModel(
            name='TypeActivite',
        ),
        migrations.DeleteModel(
            name='ValeurChamp',
        ),
    ]
