# Generated by Django 4.2.7 on 2026-03-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapportActivites', '0004_remove_photorapport_rapport_remove_valeurchamp_champ_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportactivite',
            name='description',
            field=models.TextField(blank=True, verbose_name='Desption'),
        ),
    ]
