# Generated by Django 4.2.7 on 2026-04-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapportActivites', '0004_rapportactivite_statut_validation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportactivite',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('brouillon', 'Brouillon')], default='brouillon', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='rapportactivite',
            name='statut_validation',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('brouillon', 'Brouillon')], default='en_attente', max_length=20),
        ),
    ]
