# Generated by Django 4.2.7 on 2026-03-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapportActivites', '0005_rapportactivite_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportactivite',
            name='nombre_de_joinbox_poser',
            field=models.TextField(blank=True, verbose_name='Nombre de joinbox poser'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='point_de_depart',
            field=models.TextField(blank=True, verbose_name='Point_de_part'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='type_de_brain',
            field=models.CharField(blank=True, max_length=20, verbose_name='Type de brain utilisé'),
        ),
    ]
