# Generated by Django 4.2.7 on 2026-03-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapportActivites', '0006_rapportactivite_nombre_de_joinbox_poser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportactivite',
            name='quel_brain',
            field=models.CharField(blank=True, max_length=50, verbose_name='Brains de raccordement'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='quel_joinbox',
            field=models.CharField(blank=True, max_length=50, verbose_name='Lequel des JoinBox pour le raccordement'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='tube',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tube pour le raccordement'),
        ),
    ]
