# Generated by Django 4.2.7 on 2026-03-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapportActivites', '0007_rapportactivite_quel_brain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportactivite',
            name='photo_appareils_connecte',
            field=models.ImageField(blank=True, null=True, upload_to='rapports/photos/appareils_connecte/', verbose_name='Photo appareils connectés'),
        ),
    ]
