# Generated by Django 4.2.7 on 2026-03-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapportActivites', '0008_rapportactivite_photo_appareils_connecte'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportactivite',
            name='photo_ping',
            field=models.ImageField(blank=True, null=True, upload_to='rapports/photos/ping/', verbose_name='Photo du ping'),
        ),
        migrations.AddField(
            model_name='rapportactivite',
            name='plainte_client',
            field=models.CharField(blank=True, max_length=50, verbose_name='Plainte du client'),
        ),
        migrations.AlterField(
            model_name='rapportactivite',
            name='photo_appareils_connecte',
            field=models.ImageField(blank=True, null=True, upload_to='rapports/photos/appareilsconnecte/', verbose_name='Photo appareils connectés'),
        ),
    ]
