# Generated by Django 4.2.7 on 2026-04-17 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('specialite', models.CharField(choices=[('reseau', 'Réseau et Télécom'), ('vente', 'Vente et Marketing'), ('technique', 'Support Technique'), ('gestion', 'Gestion Clientèle'), ('autre', 'Autre')], default='vente', max_length=50)),
                ('taux_commission', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
