# Generated by Django 5.2.8 on 2026-05-11 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercials', '0002_initial'),
        ('employes', '0002_remove_employe_user_employe_quartier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercial',
            options={'ordering': ['employe__nom', 'employe__prenom']},
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='date_embauche',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='email',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='quartier',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='user_account',
        ),
        migrations.AddField(
            model_name='commercial',
            name='employe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_profile', to='employes.employe'),
        ),
    ]
