# Generated by Django 4.2.7 on 2026-05-13 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercials', '0003_alter_commercial_options_remove_commercial_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercial',
            name='specialite',
        ),
    ]
