# Generated by Django 4.2.7 on 2026-03-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercials', '0003_alter_commercial_options_commercial_user_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
