# Generated by Django 4.2.7 on 2026-04-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercials', '0004_alter_commercial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
